export const chats = [
  {
    id: "0",
    name: "katrina winters",
    username: "katrina",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#ffd166",
  },
  {
    id: "1",
    name: "Faulkner Benjamin",
    username: "Faulkner",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667582834/jusTalk/dozj6zuzslllnkazqirh.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#e83e8c",
  },
  {
    id: "2",
    name: "Miranda Valentine",
    username: "Miranda",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#4eac6d",
  },
  {
    id: "3",
    name: "Tonia Clay",
    username: "Tonia",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#4eac6d",
  },
  {
    id: "4",
    name: "Dean Vargas",
    username: "Dean",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "18:50",
    avatarColor: "#ef476f",
  },
  {
    id: "5",
    name: "Norris Decker",
    username: "Norris",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "5:10",
    avatarColor: "#ef476f",
  },
  {
    id: "6",
    name: "Hendrix Martin",
    username: "Hendrix",
    image: "",
    newMessages: 2,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "9:30",
    avatarColor: "#ef476f",
  },
  {
    id: "7",
    name: "Zimmerman Langley",
    username: "Zimmerman",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "6:10",
    avatarColor: "#ffd166",
  },
  {
    id: "8",
    name: "Tonia Clay",
    username: "Tonia",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#4eac6d",
  },
  {
    id: "9",
    name: "Dean Vargas",
    username: "Dean",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "18:50",
    avatarColor: "#ef476f",
  },
  {
    id: "10",
    name: "Faulkner Benjamin",
    username: "Faulkner",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667582834/jusTalk/dozj6zuzslllnkazqirh.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#ef476f",
  },
  {
    id: "11",
    name: "Miranda Valentine",
    username: "Miranda",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#50a5f1",
  },
  {
    id: "15",
    name: "Hendrix Martin",
    username: "Hendrix",
    image: "",
    newMessages: 2,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "9:30",
    avatarColor: "#ef476f",
  },
  {
    id: "12",
    name: "Zimmerman Langley",
    username: "Zimmerman",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "6:10",
    avatarColor: "#4eac6d",
  },
  {
    id: "13",
    name: "",
    username: "Tonia",
    image: "",
    newMessages: 0,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#50a5f1",
  },
  {
    id: "14",
    name: "katrina winters",
    username: "katrina",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    newMessages: 3,
    lastMessage: "You are the best tohid!",
    lastMessageDate: "22:10",
    avatarColor: "#797c8c",
  },
];
