export const friends = [
  {
    id: "0",
    name: "katrina winters",
    username: "katrina",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    avatarColor: "#797c8c",
  },
  {
    id: "1",
    name: "Faulkner Benjamin",
    username: "Faulkner",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667582834/jusTalk/dozj6zuzslllnkazqirh.jpg",
    avatarColor: "#e83e8c",
  },
  {
    id: "2",
    name: "Miranda Valentine",
    username: "Miranda",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    avatarColor: "#4eac6d",
  },
  {
    id: "3",
    name: "Tonia Clay",
    username: "Tonia",
    image: "",
    avatarColor: "#4eac6d",
  },
  {
    id: "4",
    name: "Dean Vargas",
    username: "Dean",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    avatarColor: "#797c8c",
  },
  {
    id: "5",
    name: "Norris Decker",
    username: "Norris",
    image: "",
    avatarColor: "#ef476f",
  },
  {
    id: "6",
    name: "Hendrix Martin",
    username: "Hendrix",
    image: "",
    avatarColor: "#ef476f",
  },
  {
    id: "7",
    name: "Zimmerman Langley",
    username: "Zimmerman",
    image: "",
    avatarColor: "#ffd166",
  },
  {
    id: "8",
    name: "Tonia Clay",
    username: "Tonia",
    image: "",
    avatarColor: "#4eac6d",
  },
  {
    id: "9",
    name: "Faulkner Benjamin",
    username: "Faulkner",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667582834/jusTalk/dozj6zuzslllnkazqirh.jpg",
    avatarColor: "#e83e8c",
  },
  {
    id: "10",
    name: "Miranda Valentine",
    username: "Miranda",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    avatarColor: "#4eac6d",
  },
  {
    id: "11",
    name: "Tonia Clay",
    username: "Tonia",
    image: "",
    avatarColor: "#4eac6d",
  },
  {
    id: "12",
    name: "Dean Vargas",
    username: "Dean",
    image: "https://res.cloudinary.com/dmgb7kvmn/image/upload/v1667375697/jusTalk/zewq69s3crcubsawfsa9.jpg",
    avatarColor: "#797c8c",
  },
];
